export const FETCH_ALL_MOVIES = 'FETCH_ALL_MOVIES';
export const FETCH_MOVIES_DETAILS = 'FETCH_MOVIES_DETAILS';
export const FETCH_MOVIES_INFO = 'FETCH_MOVIE_INFO';
export const FILTER_MOVIE = 'FILTER_MOVIE';
export const ERROR_LOADING = 'ERROR_LOADING';
